dist: trusty
language: python
matrix:
    fast_finish: true
    include:
        - python: "2.7"
        - python: "3.5"
        - python: "3.6"
        - python: "3.7-dev"
        - python: "nightly"
install:
    - pip install --upgrade flake8 pylint
    - pip install --upgrade -e .
script:
    - python -m flake8 src/currex/
    # Skip pylint with development Python versions
    - |
      NIGHTLY_VERSION="3.7"
      if ! [ `python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'` == "$NIGHTLY_VERSION" ] ; then
          python -m pylint src/currex/
      fi
